# Generated by Django 5.0.1 on 2024-02-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='readable',
            field=models.BooleanField(default=False),
        ),
    ]
