# Generated by Django 5.0.1 on 2024-02-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_field_readable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
